FROM node:20-slim

# Install system dependencies for native modules
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    git \
    python3 \
    wget \
    unzip \
    libaio1 \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

RUN wget https://download.oracle.com/otn_software/linux/instantclient/2326000/instantclient-basic-linux.x64-23.26.0.0.0.zip && \
    mkdir -p /opt/oracle && \
    unzip instantclient-basic-linux.x64-23.26.0.0.0.zip -d /opt/oracle && \
    rm instantclient-basic-linux.x64-23.26.0.0.0.zip

ENV LD_LIBRARY_PATH=/opt/oracle/instantclient_23_26:$LD_LIBRARY_PATH


WORKDIR /parse-server


# Expose the default Parse Server port
EXPOSE 1337

# Set environment variables
ENV NODE_ENV=development
ENV PORT=1337

# Run the server
# To enable hot-reloading, mount the 'src' directory as a volume 
# and run 'npm run watch' in a separate process or use a tool like nodemon.
CMD ["tail", "-f", "/dev/null"]
